#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${NEMO_DB_USER} WITH ENCRYPTED PASSWORD '${NEMO_DB_PASSWORD}';
    ALTER USER ${NEMO_DB_USER} CREATEDB;
    CREATE DATABASE ${NEMO_DB_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${NEMO_DB_NAME} TO ${NEMO_DB_USER};
EOSQL
