export default {
    LEAD_TIME: "How long does it take to go from code commit to code successfully running in production",
    DEPLOYMENT_FREQUENCY: "How often does your organization deploy code",
    CHANGE_FAILURE_RATE: "What percentage of changes to production or released to users result in degraded service (e.g., lead to service impairment or service outage) and subsequently require remediation (e.g., require a hotfix, rollback, fix forward, patch)",
    TIME_TO_RESTORE: "How long does it generally take to restore service when a service incident occurs",
    MM_ITEM_EXPECTED_VALUE: "The threshold that causes the item to be failed, if gets violated.",
    PROJECT_DEFAULT_ENVIRONMENT: "The environment used for evaluation of the project's maturity.",
    MM_ITEM_VALIDITY_PERIOD: "The period (in days) an item achievement is valid in.",
    MM_ITEM_CHECKING_PERIOD: "The past period (in days) that the project is analyzed during.",
    MM_ITEM_CURRENT_VALUE: "Current evaluated value.",
    MM_ITEM_BADGE_CLOSEST_GOAL: "Closest goal date for the item",
    MM_ITEM_BADGE_PENDING_EVALUATION_REQUEST: "Has Pending Evaluation Request",
    MM_ITEM_BADGE_MANUAL_EVALUATION: "This item should be evaluated manually. It can be requested in the item's page.",
    MM_ITEM_BADGE_DORY_EVALUATION: "This item can be evaluated specifically for your product by Dory. For more details see Dory documentation.",
    MM_SNAPSHOT_DATE: "See the maturity model state at (the end of) the given date",
}