version: '3.7'
services:
  database:
    restart: unless-stopped
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nginx:
    restart: unless-stopped
    image: "nginx:1.17.5-alpine"
    volumes:
      - ../backend/static/:/backend-statics/
      - log_nginx:/var/log/nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    network_mode: host

  message_broker:
    restart: unless-stopped
    image: rabbitmq:3.8.2
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,error}]}]
    ports:
      - 5672:5672

  pgadmin:
    image: dpage/pgadmin4:4.22
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8080
    depends_on:
      - database
    ports:
      - 8080:8080
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db:
  log_nginx:
  pgadmin-data:
